open-power/ipl

- libipl/p10/ipl0.C
- Added Scratch register 3  updates 
bit 7 based on ATTR_ALLOW_ATTR_OVERRIDES 
bit 11 based ATTR_NO_XSCOM_ENFORCEMENT
> libipl: Mailbox scratch 3  register updates

- libipl/libipl.C
- libipl/libipl.H
- libipl/libipl_internal.H
- libipl/p10/common.C
- libipl/p10/ipl0.C
- libipl/p10/ipl_poweroff.C
Updated ipl_error_callback_func protype to support better
error handling support for libipl users. Existing function
only supports bool type parameter. BMC requires additional
data to create error logs with additional debug information.
Added new structure, which includes the failure reason code
and and generic buffer , which will help for future use case
to share to share debug data, like callout, guard etc.
> libipl: ipl_error_callback_func prototype change

- Makefile.am
- configure.ac
- libphal/libphal.H
- libphal/phal_dump.C
- libphal/phal_exception.H
Self Boot Engine(SBE) dump is collected from the non-
responsive SBE by executing four hardware procedures.
The output of each hardware procedure is written to
files in the path provided.
**Tests:**
**Create dump:**
```
busctl --verbose call org.open_power.Dump.Manager  /org/openpower/dump xyz.openbmc_project.Dump.Create CreateDump a{sv} 3 "com.ibm.Dump.Create.CreateParameters.DumpType" s "com.ibm.Dump.Create.DumpType.SBE" "com.ibm.Dump.Create.CreateParameters.ErrorLogId" t 0xDEADBEEF "com.ibm.Dump.Create.CreateParameters.FailingUnitId" t 0
MESSAGE "o" {
OBJECT_PATH "/xyz/openbmc_project/dump/sbe/entry/16";
};
```
**dump collection:**
```
Oct 11 05:20:22 rain98bmc phosphor-dump-manager[430]: OpenPOWER dumps are enabled
Oct 11 05:20:23 rain98bmc openpower-dump-manager[1908]: Collecting SBE …
```
> Add support for SBE dump collection

- libphal/libphal.H
- libphal/phal_exception.H
- libphal/phal_sbe.C
- libphal/utils_pdbg.C
- libphal/utils_pdbg.H
Added API to call sbe chip-op for stopping all threads
instruction on the processor.
> libphal: threadStopProc API support

- libipl/p10/ipl0.C
- The host application allowed to create two records (one for persistent
and another one for ephemeral types) per targets so, we cannot use
the entity path of the target to invalidate the target because we might
invalidate the first record of the target instead of the second one that
was expected.
- So, used the record id instead of the target entity path to clear
in the UpdateHwModel istep.
> libipl: p10: Use record id instead of the target entity path to clear

- libipl/p10/ipl0.C
Updated ATTR_BOOT_FLAGS to enable sbe chip-op failure
data collection by setting bit 4 and 5. Refer mailbox scratch 3
register definition for more details.
Tested: verified in istep mode running up to sbe_config_update
root@xxxx:/tmp# attributes export | grep BOOT_FLAGS
ATTR_BOOT_FLAGS    u32    0x8c000000
root@xxxx:/tmp# getcfam pu 283a
pu	k0:n0:s0:p00       0x8C000000
/usr/bin/edbg getcfam pu 283a
> libipl: sbe_config_update enable sbe chip-op failure data

- libphal/phal_pdbg.C
Implemented policy to not allow primary processor deconfig
action to attempt best for primary processor failure during
boot process
Tested: verified deconfig records during primary processor failure
> libphal: deconfigureTgt skip primary processor deconfig

- libphal/phal_sbe.C
Sbe stop instruction chip-op is reporting error during sbe halt state.
based on sbe  design direction in the power-off/error recovery path
If the secondary SBE is in halt state, issue sbe  hreset to get sbe
operational state to run chipop.
Tested: verified in driver verification test
> libphal: Add sbe halt state handling for threadStopProc chipop

- libipl/p10/ipl0.C
ATTR_SYS_CLOCK_DECONFIG_STATE size changed to enum 4 byte
length. updated pdbg attribute read api size 1->4.
> libipl: ATTR_SYS_CLOCK_DECONFIG_STATE size update

- libipl/p10/common.C
- libipl/p10/common.H
- libipl/p10/ipl0.C
BMC is responsible for primary processor clock initialization and clock test and host is responsible for secondary processor clock initialization and test.
Recently Hostboot added support to run non-primary processor set_ref clock support. This commit is to avoid duplicate hwp procedure execution on secondary prcessor.
Made changes to perform clock initialization and clock test only on primary processor.
> Perform clock intialization and clock test only on primary processor 

- libphal/phal_dump.C
- libphal/phal_exception.H
This commit adds a check for the SBE state before collecting the SBE dump to prevent multiple collections of the dump.
Test:
Request dump multiple times on same SBE and second time the call should return error.
root@rain104bmc:~# busctl --verbose call xyz.openbmc_project.Dump.Manager /xyz/openbmc_project/dump/sbe xyz.openbmc_project.Dump.Create CreateDump a{sv} 2 "com.ibm.Dump.Create.CreateParameters.ErrorLogId" t 0xDEADBEEF "com.ibm.Dump.Create.CreateParameters.FailingUnitId" t 0
MESSAGE "o" {
OBJECT_PATH "/xyz/openbmc_project/dump/sbe/entry/30000002";
};
root@rain104bmc:~# busctl --verbose call xyz.openbmc_project.Dump.Manager /xyz/openbmc_project/dump/sbe xyz.openbmc_project.Dump.Create CreateDump a{sv} 2 "com.ibm.Dump.Create.CreateParameters.ErrorLogId" t 0xDEADBEEF …
> Check for the SBE state before collecting dump

- libipl/p10/ipl0.C
- libphal/libphal.H
- libphal/phal_pdbg.C
In OpenBMC 1050 branch for some unavoidable reasons we have to create a mirror of open-power/ipl repo under ibm-openbmc. But that was a temporary solution and ultimately we need to move back to open-power/ipl in 1060 branch. This commit merges the missing/exclusive commits from ibm-openbmc/ipl repo into the open-power/ipl repo so that we can move back to original open-power/ipl repo in OpenBMC 1060 branch.
Missign commits which are merged are:
8c2272cc5a9030acc459e0ccb3f5e561511d344b from ibm-openbmc/ipl-1050 033bf30ce7a906e08d96790434174f706f607fb4 from ibm-openbmc/ipl-1050 (This one was ported to 1020 and 1030 as well)
The commits which were already availbale in open-power/ipl-main are: ec7d067c7dec06f61d92d186a23e9e8fe1ee4c99 from ibm-openbmc/ipl-1020 …
> Merging missing commits in open-power/ipl

- libphal/libphal.H
- libphal/phal_dump.C
Changes are been made to handle the SBE dump collection scenarios for Odyssey memory chip.
The changes are been tested on local machine with full OpenBMC build and looks good. PFA the build compeltion screenshot.
> Added logic for collecting Odyssey SBE dump

- .vscode/settings.json
- libphal/libphal.H
- libphal/phal_pdbg.C
- libphal/phal_sbe.C
This commit add support for passing the OCMB target pointer to the get dump chip-op
Tested:
Executed hardware dump collection
> Collect SBE dump from Odyssey SBE

- .vscode/settings.json
- libphal/phal_dump.C
This commit breaks down the large functions involved in the SBE dump collection process into smaller, more manageable functions.
Changes:
- Split preCollection to smaller functions
- collectSBEDump calls each of these smaller functions.
- Split collect dump to smaller functions for executing each HWP The refactor does not introduce any new functionality
Tests
root@ever6bmc:~# busctl --verbose call org.open_power.Dump.Manager /org/openpower/dump xyz.openbmc_project.Dump.Create CreateDump a{sv} 3  "com.ibm.Dump.Create.CreateParameters.DumpType" s "com.ibm.Dump.Create.DumpType.SBE" "com.ibm.Dump.Create.CreateParameters.ErrorLogId" t 0xDEADBEEF "com.ibm.Dump.Create.CreateParameters.FailingUnitId" t 2
MESSAGE "o" {
OBJECT_PATH "/xyz/openbmc_project/dump/sbe/entry/30000003";
};
Jan 16 15:30:44 …
> Restructure SBE dump collection for improved maintainability

- libphal/phal_dump.C
We have now OdySsey chip along with the existing p10 which supports SBE dump collection. In future we may have more varieties of chips. So the new code to support Odyssey operation has been added.
Test:
busctl --verbose call org.open_power.Dump.Manager /org/openpower/dump xyz.openbmc_project.Dump.Create CreateDump a{sv} 3 "com.ibm.Dump.Create.CreateParameters.DumpType" s "com.ibm.Dump.Create.DumpType.MemoryBufferSBE" "com.ibm.Dump.Create.CreateParameters.ErrorLogId" t 0xDEADBEEF "com.ibm.Dump.Create.CreateParameters.FailingUnitId" t 2
MESSAGE "o" {
OBJECT_PATH "/xyz/openbmc_project/dump/msbe/entry/40000003";
};
Jan 29 08:53:46 phosphor-dump-manager[498]: Create dump type(sbedump) with id(40000003) …
> Odyssey SBE dump collection support code added

- libphal/phal_dump.C
To read PIBMEM dump data for Odyssey chip we need 512KB of length. The code in dump collection section has been changed accordingly.
Test results are attached
[sbe-debug_parser_log.log](https://github.com/open-power/ipl/files/14533355/sbe-debug_parser_log.log)
> Read buffer length size increased to read PIBMEM dumps for Odyssey

- libphal/libphal.H
- libphal/phal_exception.C
- libphal/phal_exception.H
- libphal/phal_sbe.C
1) Loop through all the FFDC packets
2) Capture packets matching the slid number
3) For a particular slid check all the packets for severity 4) Pick the highest severity from all the severity
Tested:
slid 1 has severity 40 and slide 3 has 4 packets
ensured pel1 is created with severity 40
ensured pel2 is created with highest severity 20
chip-op success received pending FFDC from SBE
IPL POZ capturePOZFFDC slid=1
IPL POZ capturePOZFFDC severity=40
IPL POZ capturePOZFFDC slid=3
IPL POZ capturePOZFFDC severity=10
IPL POZ capturePOZFFDC slid=3
IPL POZ capturePOZFFDC severity=20
IPL POZ capturePOZFFDC slid=3
IPL POZ capturePOZFFDC severity=20
IPL POZ capturePOZFFDC slid=3
IPL POZ capturePOZFFDC severity=20
IPL POZ capturePOZFFDC split severity =0x40
IPL POZ capturePOZFFDC split severity =0x20 …
> POZ: capture pel severity from FFDC packet

- libphal/phal_dump.C
Earlier we used to compare the FAPI unit position with the failing unit ID for Odyssey SBE dump collection, while for P10 chip, we compared it with PDBG target index. Now along with changes made in PDBG we only compare PDBG target index with the failing unit ID for both the P10 and Odyssey chip while collecting SBE dump.
Test Results:
odyssey
p[62]
mp[6,7]
perv[28,35]
p[2]
mp[68,69]
perv[51,58]
p[6]
mp[70,71]
perv[60,67]
/usr/bin/edbg ecmdquery chips -dc
root:/tmp/src# busctl --verbose call org.open_power.Dump.Manager /org/openpower/dump xyz.openbmc_project.Dump.Create CreateDump a{sv} 3 "com.ibm.Dump.Create.CreateParameters.DumpType" s "com.ibm.Dump.Create.DumpType.MemoryBufferSBE" "com.ibm.Dump.Create.CreateParameters.ErrorLogId" t 0xDEADBEEF …
> libphal: Changing FAPI unit pos to PDBG traget index

- libphal/phal_dump.C
As with the latest changes in PDBG and PDATA for the Odyssey chip indexing we are not anymore considering the FAPI unit position to determine the Ody chip position thus removed the function from ipl code to get the same as it became redundant.
No functionality has been changed in effect thus nothing to be tested
> libphal: Removing unnecessary code to get the FAPI unit position

- configure.ac
- libphal/libphal.H
- libphal/phal_exception.H
- libphal/phal_pdbg.C
We need to capture the DRAM manufacturer ID in the PEL (error log) whenever a DIMM is callout/guarded/deconfigured. This is essential for identifying the DRAM manufacturer since IBM sources DRAM from different vendors.
The VPD will store the DRAM manufacturer ID in the DIMM inventory using the VINI DBus interface. The PEL daemon must retrieve this VPD keyword and add it to a new user data section.
The PEL daemon is unable to determine if a callout/guarded/deconfigured location code corresponds to a DIMM. Therefore, PHAL needs to offer an API that can return the FRU type by utilizing the PHAL device tree.
Change-Id: I738697c2b28885419fdcda60814e8ea7312ac8b2
> libphal: PHAL API for returning FRU Type

- libphal/log.C
- libphal/phal_pdbg.C
libphal trace is broken and the traces are not flushed to the journal. So, using fflush to fix this issue.
Also, log() method is expecting a c string. so, type casting the argument.
Change-Id: I61b77f71a02504a86fc144832f6fa2cb1410a21c
Signed-off-by: SwethaParasa <parasa.swetha1@ibm.com>
> libphal: Fix libphal traces

- libphal/phal_pdbg.C
We are modifying the logging behavior for the getFRUType API. Instead 
of logging an error trace when a location code does not exist in the 
PHAL device tree, we will now log a debug trace. This change is 
intended to reduce unnecessary entries in the journal.
Change-Id: I7829f968ec36000f6961c92d5b9a7e8cd961d109
Signed-off-by: SwethaParasa <parasa.swetha1@ibm.com>
> libphal:Replace error trace with debug trace for getFRUType API calls
